[fix][sdk] After dropTable, clean up routeTable information and cache
dingodb/dingo-store pull request #125
Opened 2023-03-29 06:27 UTC by wt0530

2023-03-29 14:10 UTC, astor-oss requested changes

2023-03-29 14:10 UTC, astor-oss commented on java/dingo-sdk/src/main/java/io/dingodb/client/ServiceOperation.java
> +                return null;
表不存在也不来点日志？否则到时候都没办法看到异常啊

2023-03-29 14:10 UTC, astor-oss commented on java/dingo-sdk/src/main/java/io/dingodb/client/ServiceOperation.java
> +    public synchronized void updateCacheOfTableDefinition(final String tableName, final Table tableDef) {
这个类 synchronized 搞的好多，每次查表都得加锁，到时候看看是否可以优化一下

2023-03-29 14:10 UTC, astor-oss commented on java/dingo-sdk/src/main/java/io/dingodb/client/ServiceOperation.java
> +            return new Result(false, null);
补充一下第二个参数的错误信息

2023-03-29 15:00 UTC, ketor approved these changes
LGTM.

2023-03-30 03:17 UTC, ketor approved these changes
LGTM

2023-03-30 03:24 UTC, astor-oss approved these changes

2023-03-30 03:24 UTC, merged