[feat][proto] Add version service provides listen for changes in vesion.
dingodb/dingo-store pull request #126
Opened 2023-03-29 12:18 UTC by JYcz

[feat][proto] Add version service provides listen for changes in vesion.

2023-03-29 14:00 UTC, astor-oss reviewed
一些意见，请参考

2023-03-29 14:00 UTC, astor-oss commented on src/server/version_service.cc
> +  std::unique_lock<std::mutex> lock(mutex_);
之前用的比较的是 BAIDU_SCOPED_LOCK
请参考：https://github.com/apache/brpc/blob/master/src/butil/scoped_lock.h

2023-03-30 10:40 UTC, ketor requested changes

2023-03-30 10:40 UTC, ketor commented on proto/version.proto
> +}
proto这部分建议先不要新增service，复用现有的meta.proto，直接在meta_service中增加接口，从逻辑上说meta_service代表了SQL和SDK所需要的rpc接口。

meta service会默认选择coordinator leader提供服务，同时meta_service与coordinator_control已经完成了对接。

2023-03-30 10:40 UTC, ketor commented on proto/version.proto
> +}
具体的rpc协议的内容还需要再讨论一下，直接把交互的数据结构穷举确定出来，前期先做1～2个最必要的接口，后面逐步增加。

Coordinator的CPU压力较大，从性能的容量来说相当于是单点，因此需要在设计层面尽量减少在coordinator一侧进行的计算，不必须的计算下推到节点数量更多的SDK层面。

2023-03-30 11:08 UTC, JYcz commented on proto/version.proto
> +}
自动选择leader跟metaService没啥关系吧，自动选leader那是serviceConnector的事，而且总共就两个基本的接口也没加啥不必要的啊。

2023-03-30 11:14 UTC, JYcz commented on src/server/version_service.cc
> +    version_listener->condition.wait_for(lock, std::chrono::microseconds(std::chrono::seconds(wait_seconds)).count());
waitQueue有超时时间么，我这实现的只是通用的服务，map里的实现跟这里关系不大，这里只做类似long polling的实现，上次说的时候就是用condition阻塞。

2023-04-01 07:37 UTC, ketor commented on src/server/version_service.cc
> +    version_listener->condition.wait_for(lock, std::chrono::microseconds(std::chrono::seconds(wait_seconds)).count());
超时可以通过background bthread对waitQueue进行处理的时候加以实现。如前文和代码所述，在brpc的编程框架内，使用条件变量这种模式并不是一个合适的选择，brpc的处理流程是基于协程的模式设计的，可以参考braft对于brpc的使用方法，使用closure进行流转就可以，closure的所有权转移走之后，虽然函数返回了，但其实request仍然是阻塞住的，直至closure被调用后才返回response。从线程调度来说，实际上线程已经的控制权已经交给其他的协程继续处理了，线程不会被阻塞。
基于协程的这种设计模式，与一般的多线程处理request的模式有区别，所以这里并不需要用条件变量来阻塞线程。

2023-04-01 07:47 UTC, ketor commented on proto/version.proto
> +}
meta_service需要跟raft状态机对接，以确定所在coordinator节点的角色是leader还是follower，如果当前是follower，需要通过raft接口获取到leader地址，生成response把leader_location返回给SDK。
需要service push的数据结构实际上都是meta里的数据结构，直接集成到meta_service里也是合理的。

2023-04-03 02:24 UTC, JYcz commented on src/server/version_service.cc
> +    version_listener->condition.wait_for(lock, std::chrono::microseconds(std::chrono::seconds(wait_seconds)).count());
每个请求进来是bthread所以并没有阻塞线程

2023-04-03 02:26 UTC, JYcz commented on proto/version.proto
> +}
完全解耦的两个模块没必要放在一起

2023-04-03 02:35 UTC, JYcz commented on proto/version.proto
> +}
非要放一起会显得很乱

2023-04-06 05:56 UTC, ketor requested changes
Request changes

2023-04-06 05:56 UTC, ketor commented on src/server/version_service.cc
> +      sleep(1);
maybe bthread_usleep here

2023-04-07 03:39 UTC, ketor approved these changes
LGTM

2023-04-07 03:39 UTC, merged