[feat][common] add serial c++
dingodb/dingo-store pull request #152
Opened 2023-04-07 07:21 UTC by kevinguo1989

2023-04-08 17:56 UTC, ketor requested changes
Please make all code conform to the google c++ style.

2023-04-08 18:08 UTC, ketor commented
Please check the file name format of existing files, and fix file names to lower case ones.

2023-04-10 09:20 UTC, ketor requested changes
Request changes

2023-04-10 09:20 UTC, ketor commented on src/serial/record_encoder.cc
> +    Buf *keyBuf = new Buf(key_buf_size);
这里的keyBuf缺少delete，需要考虑一下如何管理它的内存

2023-04-10 09:20 UTC, ketor commented on src/serial/record_decoder.cc
> +    Buf *value_buf = new Buf(keyvalue->getValue());
key_buf和value_buf需要考虑如何delete

2023-04-10 09:20 UTC, ketor commented on src/serial/record_decoder.cc
> +        //"Wrong Common Id"
这里是否需要return？

2023-04-10 09:20 UTC, ketor commented on src/serial/schema/long_schema.h
> +class DingoSchema<long*> : public BaseSchema
long在C++中的长度是不确定的，与平台相关，需要修改为uint32_t, uint64_t这种长度确定的类型。

2023-04-10 09:20 UTC, ketor commented on src/serial/schema/integer_schema.cc
> +int DingoSchema<int*>::getDataLength() {
int的长度是与平台相关的，这里需要确定具体的位宽，修改为uint32_t, uint64_t这种类型

2023-04-11 02:13 UTC, kevinguo1989 commented
关闭pr，待修改完后重新提交

2023-04-11 02:13 UTC, closed without merging