[refactor][store] Refactor DeleteRange API.
dingodb/dingo-store pull request #175
Opened 2023-04-14 07:40 UTC by yuhaijun999

1. Add the number of returned deleted data.
2. Handle various range returns.
3. Process the last piece of data.

2023-04-15 13:47 UTC, ketor requested changes
Request changes

2023-04-15 13:47 UTC, ketor commented on proto/store.proto
> +  // If max_fetch_cnt > 0, it means to return scan_id and data. Note that in this way, the return will be slower because
KvScanContinueResponse里没有scan_id，这里的注释说会返回scan_id and data，是注释错了么？

2023-04-15 13:47 UTC, ketor commented on src/common/helper.cc
> +// original_key + 1. note overflow
how could the caller of this function to note overflow?

2023-04-15 13:47 UTC, ketor commented on src/common/helper.cc
> +  *key = std::move(s);  // NOLINT
这个std::move是否没有必要，下面一行紧接着就是一次赋值。

2023-04-15 13:47 UTC, ketor commented on src/common/helper.cc
> +  std::string s(key.size(), static_cast<char>(0xFF));
这个函数直接判断key里面的内容是否每一个位置都是FF是否是更快的？ 这样可以少一次构造析构，仅作为建议。

另外，是否有必要判断KeyIsEndOFAllTable是存疑的，这个判断很可能是没有意义的。具体请看后文的review建议。

2023-04-15 13:47 UTC, ketor commented on src/engine/raw_rocks_engine.cc
> +  if (Helper::KeyIsEndOfAllTable(range.range().start_key()) || Helper::KeyIsEndOfAllTable(range.range().end_key())) {
这里可以不用判断start_key了，此时start_key必然小于end_key了。

2023-04-15 13:47 UTC, ketor commented on src/engine/raw_rocks_engine.cc
> +}
函数之间最好有空行

2023-04-15 13:47 UTC, ketor commented on src/engine/raw_rocks_engine.cc
> +  uint64_t internal_count = 0;
internal_count是否有用，没有看到有用到这个变量的位置

2023-04-15 13:47 UTC, ketor commented on src/engine/raw_rocks_engine.cc
> +  if (Helper::KeyIsEndOfAllTable(real_start_key) || Helper::KeyIsEndOfAllTable(real_end_key)) {
real_start_key这里没有必要判断了。

2023-04-15 13:47 UTC, ketor commented on proto/raft.proto
> +  repeated dingodb.pb.common.RangeExt ranges = 2;
store.proto里面的RangeExt只有1个，这里为何会是多个呢？

2023-04-15 13:47 UTC, ketor commented on src/handler/raft_handler.cc
> +        delete_count = delete_counts[0];
这里为何只取delete_count[0]，vector里其他的element没用么？

2023-04-15 13:47 UTC, ketor commented on src/handler/raft_handler.cc
> +      break;
如果有多个range需要delete range，前面几个成功了，最后1个失败了。 那前面删除失败的数据是否应该rollback？ 现在这样的实现导致了没有原子性了，多个range应该是全部success or 全部 fail才符合语义。

2023-04-15 13:47 UTC, ketor commented on src/handler/raft_handler.cc
> +    if (!status.ok() || 0 == delete_count) {
如果第一个range的count=0，后面的range就不会delete range了，然后返回的结果是delete ranges成功。
这里还是有之前在raft.proto里提的疑问，为何这个请求在raft里是repeated ranges？

2023-04-15 13:47 UTC, ketor commented on src/scan/scan.cc
> +    if (!range.with_start() || !range.with_end()) {
这里是基于什么需求要判断illegal paramter的呢？

2023-04-15 13:47 UTC, ketor commented on src/server/store_service.cc
> +    }
这里一堆的参数判断，是否和后面处理过程中的参数判断存在重复？

2023-04-15 13:47 UTC, ketor commented on src/server/store_service.cc
> +    }
这里最重要的需要验证start_key, end_key是否在region的Range内，但是没有看到这个验证。
实际上只要考虑了region的Range范围的验证，就不需要在判断end_key是否是0xFFFFFFFFF.......了。
因为table_id是由Coordinator分配的，不会超过uint64_t的最大值。
按照现在的编码规则，end_key不可能是0xFFFFFFFF开头的。

2023-04-16 01:51 UTC, astor-oss requested changes

2023-04-16 01:51 UTC, astor-oss commented on proto/common.proto
> +message RangeExt {
建议将 RangeExt 改为 RangeWithOptions

2023-04-16 01:51 UTC, astor-oss commented on proto/raft.proto
> +  repeated uint64 delete_counts = 2;
编号默认都从1开始吧

2023-04-16 01:51 UTC, astor-oss commented on proto/store.proto
> +  uint64 delete_count = 2;
前面是 repeteated这里是单个？

2023-04-16 01:51 UTC, astor-oss commented on src/engine/raw_rocks_engine.cc
> +    DINGO_LOG(ERROR) << butil::StringPrintf("start_key or end_key empty. not support");
最好把那个是空的打印出来？否则保存也不知道到底谁空了

2023-04-16 01:51 UTC, astor-oss commented on src/handler/raft_handler.cc
>      if (!status.ok()) {
一次请求多个DeleteRange，如果一个失败了，直接退出是不是有问题？整个操作的返回值是成功还是失败？

2023-04-16 01:51 UTC, astor-oss commented on src/server/store_service.cc
> +    if (!request->range().with_start() || !request->range().with_end()) {
能不能把 范围比较的逻辑都抽成函数，感觉很多地方都在用

2023-04-17 01:22 UTC, yuhaijun999 commented on src/common/helper.cc
> +  *key = std::move(s);  // NOLINT
优化性能 很有必要

2023-04-17 02:08 UTC, yuhaijun999 commented on proto/store.proto
> +  // If max_fetch_cnt > 0, it means to return scan_id and data. Note that in this way, the return will be slower because
是的 我把scan_id 去掉了 谢谢你

2023-04-17 02:11 UTC, yuhaijun999 commented on src/common/helper.cc
> +// original_key + 1. note overflow
函数的返回值 会标记 true 合法 false 非法

2023-04-17 02:13 UTC, yuhaijun999 commented on src/common/helper.cc
> +  *key = std::move(s);  // NOLINT
我再说清楚点 是服用s 的内存  key 就不需要再次申请内存了 减少内存申请

2023-04-17 02:15 UTC, yuhaijun999 commented on src/common/helper.cc
> +  std::string s(key.size(), static_cast<char>(0xFF));
这个地方最好是调用memcmp 因为 memcmp 底层是用汇编做的优化 肯定是比我们手动比较性能强劲 当然我们这里确实会构造一次内存 可能会慢 这个我不确定

2023-04-17 02:22 UTC, yuhaijun999 commented on src/engine/raw_rocks_engine.cc
> +  if (Helper::KeyIsEndOfAllTable(range.range().start_key()) || Helper::KeyIsEndOfAllTable(range.range().end_key())) {
从严谨的角度看 start_key = "0xFF, 0xFF, 0FF， 0xFF"  end_key = "0xFF, 0xFF, 0FF，0xFF, 0xFF, 0xFF" 两个都需要做参数检查的

2023-04-17 02:24 UTC, yuhaijun999 commented on src/engine/raw_rocks_engine.cc
> +}
我改下 这行

2023-04-17 02:32 UTC, yuhaijun999 commented on src/engine/raw_rocks_engine.cc
> +  uint64_t internal_count = 0;
哥哥  你是对的 这个已经没用了 我放弃他

2023-04-17 02:34 UTC, yuhaijun999 commented on src/engine/raw_rocks_engine.cc
> +  if (Helper::KeyIsEndOfAllTable(real_start_key) || Helper::KeyIsEndOfAllTable(real_end_key)) {
这个同上 需要做检查

2023-04-17 02:34 UTC, yuhaijun999 commented on proto/raft.proto
> +  repeated dingodb.pb.common.RangeExt ranges = 2;
这个是子辉写的 我需要和他同步下

2023-04-17 02:35 UTC, yuhaijun999 commented on src/handler/raft_handler.cc
> +        delete_count = delete_counts[0];
这里 默认是只有一个 数据 这个我再和子辉 同步下

2023-04-17 02:35 UTC, yuhaijun999 commented on src/handler/raft_handler.cc
> +      break;
同上  你是对的 哥哥

2023-04-17 02:36 UTC, yuhaijun999 commented on src/handler/raft_handler.cc
> +    if (!status.ok() || 0 == delete_count) {
好的 我确认下

2023-04-17 02:38 UTC, yuhaijun999 commented on src/scan/scan.cc
> +    if (!range.with_start() || !range.with_end()) {
如果start_key == end_key 那么仅仅 只有一种情况  就是 就是 我们只需要 这个前缀的key 其他全部丢弃
如：  start_key == end_key = "key" 那么 我们只获取 "keyXXXX" 的数据 其他 均是非法的

2023-04-17 02:41 UTC, yuhaijun999 commented on src/server/store_service.cc
> +    }
我们只基于这样思考 底层     butil::Status KvDeleteRange(const pb::common::RangeExt& range) override; 可以内部用也可以外部用  在这里做参数检查的用意是 做初步检查 如果报错 直接返回 节省了服务开销

2023-04-17 02:42 UTC, yuhaijun999 commented on src/server/store_service.cc
> +    }
实际上如果放到这里的话 会有一大部分业务代码移植过来 合适吗？

2023-04-17 02:42 UTC, yuhaijun999 commented on proto/common.proto
> +message RangeExt {
这个是子辉建议修改的名字 我和他同步下

2023-04-17 02:50 UTC, yuhaijun999 commented on proto/raft.proto
> +  repeated uint64 delete_counts = 2;
是的  应该从1开始 我改下

2023-04-17 02:50 UTC, yuhaijun999 commented on proto/store.proto
> +  uint64 delete_count = 2;
这里应该是单个 我稍后和子辉 碰下

2023-04-17 02:53 UTC, yuhaijun999 commented on src/engine/raw_rocks_engine.cc
> +    DINGO_LOG(ERROR) << butil::StringPrintf("start_key or end_key empty. not support");
你是对个 我加上

2023-04-17 02:55 UTC, yuhaijun999 commented on src/handler/raft_handler.cc
>      if (!status.ok()) {
你是对个 目前假设仅有一个请求 我再和 子辉碰下

2023-04-17 02:56 UTC, yuhaijun999 commented on src/server/store_service.cc
> +    if (!request->range().with_start() || !request->range().with_end()) {
我把他抽象出来 放到common 中

2023-04-17 03:01 UTC, yuhaijun999 commented on proto/common.proto
> +message RangeExt {
子辉 说 可以 那我就改成 RangeWithOptions 这个了

2023-04-17 03:35 UTC, yuhaijun999 commented on src/common/helper.cc
> +  std::string s(key.size(), static_cast<char>(0xFF));
哥哥 你是的对的

2023-04-17 10:55 UTC, ketor approved these changes

2023-04-18 03:31 UTC, astor-oss approved these changes

2023-04-18 03:47 UTC, merged