[fix][store] Fix KvBatchPutIfAbsent API.
dingodb/dingo-store pull request #182
Opened 2023-04-18 10:02 UTC by yuhaijun999

[fix][store] Fix KvBatchPutIfAbsent API.

2023-04-18 10:19 UTC, astor-oss requested changes

2023-04-18 10:19 UTC, astor-oss commented on src/engine/raw_rocks_engine.cc
> +    butil::Status status = StoreServiceImpl::KvDeleteRangeParamCheck(range, &real_start_key, &real_end_key);
raw_rocks_engine作为底层代码，不应该依赖上层逻辑

2023-04-18 10:28 UTC, yuhaijun999 commented on src/engine/raw_rocks_engine.cc
> +    butil::Status status = StoreServiceImpl::KvDeleteRangeParamCheck(range, &real_start_key, &real_end_key);
嗯 这个放到 raw_rocks_engine.h 中合适吗

2023-04-19 03:14 UTC, astor-oss approved these changes

2023-04-19 03:39 UTC, merged