[feat][store] Serialization and deserialization support list type
dingodb/dingo-store pull request #455
Opened 2023-08-08 10:28 UTC by githubgxll

[feat][store] Serialization and deserialization support list type

2023-08-08 12:47 UTC, ketor requested changes

2023-08-08 12:47 UTC, ketor commented on src/serial/schema/string_list_schema.cc
> +    // 遍历data,并调用InternalEmlementEncodeValue函数，以便序列化vector中的每个元素
Please remove chinese comments.

2023-08-08 14:14 UTC, astor-oss approved these changes

2023-08-09 02:35 UTC, ketor approved these changes
LGTM

2023-08-09 02:35 UTC, merged